//! pacman's version comparison, transcribed from `libalpm/version.c`.
//!
//! A version is `[epoch:]pkgver[-pkgrel]`. Epochs compare as integers, then
//! `pkgver` and, only when both sides carry one, `pkgrel`, each by pacman's
//! variant of rpm's segment walk: runs of digits compare numerically, runs of
//! letters compare as strings, a `~` sorts before anything, and a trailing
//! alphabetic segment loses to an empty one (`1.0` is newer than `1.0a`,
//! because `a` is read as a pre-release). The Arch and AUR sources use this
//! to decide what is an update; `tests/vercmp.rs` holds a table generated by
//! running the real `vercmp` and failing on any disagreement.

use std::cmp::Ordering;

/// Compare two full pacman versions. `Ordering::Greater` means `a` is newer.
pub fn vercmp(a: &str, b: &str) -> Ordering {
    let (ea, va, ra) = split(a);
    let (eb, vb, rb) = split(b);
    let epoch = ea.cmp(&eb);
    if epoch != Ordering::Equal {
        return epoch;
    }
    let ver = rpmvercmp(va, vb);
    if ver != Ordering::Equal {
        return ver;
    }
    match (ra, rb) {
        (Some(ra), Some(rb)) => rpmvercmp(ra, rb),
        _ => Ordering::Equal,
    }
}

/// `a` is strictly newer than `b`.
pub fn is_newer(a: &str, b: &str) -> bool {
    vercmp(a, b) == Ordering::Greater
}

/// `[epoch:]pkgver[-pkgrel]` into its three parts. An absent epoch is 0; an
/// epoch that is not a number is 0 too, which is what pacman does.
fn split(v: &str) -> (u64, &str, Option<&str>) {
    let (epoch, rest) = match v.split_once(':') {
        Some((e, rest)) => (e.parse::<u64>().unwrap_or(0), rest),
        None => (0, v),
    };
    let (ver, rel) = match rest.rsplit_once('-') {
        Some((ver, rel)) => (ver, Some(rel)),
        None => (rest, None),
    };
    (epoch, ver, rel)
}

/// pacman's `rpmvercmp`, byte for byte in behaviour.
pub fn rpmvercmp(a: &str, b: &str) -> Ordering {
    if a == b {
        return Ordering::Equal;
    }
    let one = a.as_bytes();
    let two = b.as_bytes();
    let (mut i, mut j) = (0usize, 0usize);

    let is_alnum = |c: u8| c.is_ascii_alphanumeric();

    while i < one.len() || j < two.len() {
        // Separators are skipped; they carry no meaning of their own.
        while i < one.len() && !is_alnum(one[i]) && one[i] != b'~' {
            i += 1;
        }
        while j < two.len() && !is_alnum(two[j]) && two[j] != b'~' {
            j += 1;
        }
        // A tilde sorts before everything, including the end of the string.
        let ta = i < one.len() && one[i] == b'~';
        let tb = j < two.len() && two[j] == b'~';
        if ta || tb {
            if ta && tb {
                i += 1;
                j += 1;
                continue;
            }
            return if ta { Ordering::Less } else { Ordering::Greater };
        }
        if i >= one.len() || j >= two.len() {
            break;
        }
        let (si, sj) = (i, j);
        let isnum;
        if one[i].is_ascii_digit() {
            while i < one.len() && one[i].is_ascii_digit() {
                i += 1;
            }
            while j < two.len() && two[j].is_ascii_digit() {
                j += 1;
            }
            isnum = true;
        } else {
            while i < one.len() && one[i].is_ascii_alphabetic() {
                i += 1;
            }
            while j < two.len() && two[j].is_ascii_alphabetic() {
                j += 1;
            }
            isnum = false;
        }
        // Segments of different kinds: the numeric one is newer.
        if sj == j {
            return if isnum {
                Ordering::Greater
            } else {
                Ordering::Less
            };
        }
        let seg1 = &one[si..i];
        let seg2 = &two[sj..j];
        let rc = if isnum {
            let s1 = strip_zeros(seg1);
            let s2 = strip_zeros(seg2);
            s1.len().cmp(&s2.len()).then_with(|| s1.cmp(s2))
        } else {
            seg1.cmp(seg2)
        };
        if rc != Ordering::Equal {
            return rc;
        }
    }

    if i >= one.len() && j >= two.len() {
        return Ordering::Equal;
    }
    // A remaining alphabetic string never beats an empty one.
    let one_empty = i >= one.len();
    let two_alpha = j < two.len() && two[j].is_ascii_alphabetic();
    let one_alpha = i < one.len() && one[i].is_ascii_alphabetic();
    if (one_empty && !two_alpha) || one_alpha {
        Ordering::Less
    } else {
        Ordering::Greater
    }
}

fn strip_zeros(s: &[u8]) -> &[u8] {
    let n = s.iter().take_while(|&&c| c == b'0').count();
    &s[n..]
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cmp(a: &str, b: &str) -> i8 {
        match vercmp(a, b) {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        }
    }

    #[test]
    fn the_cases_from_pacman_s_own_test_suite() {
        // From pacman's test/util/vercmptest.sh.
        let table: &[(&str, &str, i8)] = &[
            ("1.5.0", "1.5.0", 0),
            ("1.5.1", "1.5.0", 1),
            ("1.5.1", "1.5", 1),
            ("1.5.0-1", "1.5.0-1", 0),
            ("1.5.0-1", "1.5.0-2", -1),
            ("1.5.0-1", "1.5.1-1", -1),
            ("1.5.0-2", "1.5.1-1", -1),
            ("1.5", "1.5-1", 0),
            ("1.5-1", "1.5", 0),
            ("1.1-1", "1.1", 0),
            ("1.0-1", "1.1", -1),
            ("1.1-1", "1.0", 1),
            ("1.5b-1", "1.5-1", -1),
            ("1.5b", "1.5", -1),
            ("1.5b-1", "1.5", -1),
            ("1.5b", "1.5.1", -1),
            ("1.0a", "1.0alpha", -1),
            ("1.0alpha", "1.0b", -1),
            ("1.0b", "1.0beta", -1),
            ("1.0beta", "1.0rc", -1),
            ("1.0rc", "1.0", -1),
            ("1.5.0", "1.5", 1),
            ("1.5.0", "1.5.a", 1),
            ("1.5.0", "1.5", 1),
            ("1.5a", "1.5", -1),
            ("1.0", "1.0.0", -1),
            ("1", "1.0", -1),
            ("1.0.0", "1", 1),
            ("1", "1.0", -1),
            ("1.0", "1.0", 0),
            ("1.0-1", "1.0-1", 0),
            ("1.0-1", "2.0-1", -1),
            ("1.0", "1.0a", 1),
            ("1.0a", "1.0b", -1),
            ("1.0b", "1.0a", 1),
            ("1:1.0", "1.0", 1),
            ("1:1.0", "2.0", 1),
            ("1:1.0", "1:1.0", 0),
            ("1:1.0", "1:2.0", -1),
            ("0:1.0", "1.0", 0),
            ("1.0~rc1", "1.0", -1),
            ("1.0~rc1", "1.0~rc2", -1),
            ("1.0~rc1", "1.0~", 1),
            ("1.0~", "1.0", -1),
            ("1.0~~", "1.0~", -1),
            ("1.0~rc1", "1.0~rc1", 0),
            ("2.0.3", "2.0.3.1", -1),
            ("1.0.0.87", "1.0.0.87-3", 0),
            ("20260821", "20260820-1", 1),
            ("r16.961702d-1", "r17.abc-1", -1),
            ("2.1.0-2", "2.1.0", 0),
            ("0.10.7-1", "0.9.9-1", 1),
        ];
        for (a, b, want) in table {
            assert_eq!(cmp(a, b), *want, "vercmp({a}, {b})");
            assert_eq!(cmp(b, a), -*want, "vercmp({b}, {a})");
        }
    }
}
