//! pacman's version comparison, transcribed from `libalpm/version.c`.
//!
//! A version is `[epoch:]pkgver[-pkgrel]`. Epochs compare as integers, then
//! `pkgver` and, only when both sides carry one, `pkgrel`, each by pacman's
//! variant of rpm's segment walk: runs of digits compare numerically, runs of
//! letters compare as strings, every other character is a separator (so `~`
//! is not special here, unlike in dpkg), and a trailing alphabetic segment
//! loses to an empty one (`1.0` is newer than `1.0a`). The Arch and AUR sources use this
//! to decide what is an update; `tests/vercmp.rs` holds a table generated by
//! running the real `vercmp` and failing on any disagreement.

use std::cmp::Ordering;

/// Compare two full pacman versions. `Ordering::Greater` means `a` is newer.
pub fn vercmp(a: &str, b: &str) -> Ordering {
    let (ea, va, ra) = split(a);
    let (eb, vb, rb) = split(b);
    let epoch = rpmvercmp(ea, eb);
    if epoch != Ordering::Equal {
        return epoch;
    }
    let ver = rpmvercmp(va, vb);
    if ver != Ordering::Equal {
        return ver;
    }
    match (ra, rb) {
        (Some(ra), Some(rb)) => rpmvercmp(ra, rb),
        _ => Ordering::Equal,
    }
}

/// `a` is strictly newer than `b`.
pub fn is_newer(a: &str, b: &str) -> bool {
    vercmp(a, b) == Ordering::Greater
}

/// `[epoch:]pkgver[-pkgrel]` into its three parts, as pacman's `parseEVR`:
/// the epoch is a run of digits before a colon and is "0" when absent or
/// when what precedes the colon is not digits.
fn split(v: &str) -> (&str, &str, Option<&str>) {
    let digits = v.bytes().take_while(u8::is_ascii_digit).count();
    let (epoch, rest) = if v.as_bytes().get(digits) == Some(&b':') {
        let e = &v[..digits];
        (if e.is_empty() { "0" } else { e }, &v[digits + 1..])
    } else {
        ("0", v)
    };
    let (ver, rel) = match rest.rsplit_once('-') {
        Some((ver, rel)) => (ver, Some(rel)),
        None => (rest, None),
    };
    (epoch, ver, rel)
}

/// pacman's `rpmvercmp`, transcribed from `libalpm/version.c`. Nothing here
/// is a design choice: every branch is pacman's, including the ones that
/// look odd (`~` is a separator like any other, so `1.0~rc1` is *newer* than
/// `1.0`; a trailing `+` beats nothing).
pub fn rpmvercmp(a: &str, b: &str) -> Ordering {
    if a == b {
        return Ordering::Equal;
    }
    let one = a.as_bytes();
    let two = b.as_bytes();
    let (mut i, mut j) = (0usize, 0usize);

    while i < one.len() && j < two.len() {
        let (pi, pj) = (i, j);
        while i < one.len() && !one[i].is_ascii_alphanumeric() {
            i += 1;
        }
        while j < two.len() && !two[j].is_ascii_alphanumeric() {
            j += 1;
        }
        // Ran to the end of either: finished with the loop.
        if !(i < one.len() && j < two.len()) {
            break;
        }
        // Different separator lengths: also finished, and the shorter
        // separator is the older version.
        if (i - pi) != (j - pj) {
            return if (i - pi) < (j - pj) {
                Ordering::Less
            } else {
                Ordering::Greater
            };
        }
        let (si, sj) = (i, j);
        let isnum = if one[i].is_ascii_digit() {
            while i < one.len() && one[i].is_ascii_digit() {
                i += 1;
            }
            while j < two.len() && two[j].is_ascii_digit() {
                j += 1;
            }
            true
        } else {
            while i < one.len() && one[i].is_ascii_alphabetic() {
                i += 1;
            }
            while j < two.len() && two[j].is_ascii_alphabetic() {
                j += 1;
            }
            false
        };
        // Two segments of different kinds: the numeric one is newer.
        if sj == j {
            return if isnum {
                Ordering::Greater
            } else {
                Ordering::Less
            };
        }
        let mut seg1 = &one[si..i];
        let mut seg2 = &two[sj..j];
        if isnum {
            seg1 = strip_zeros(seg1);
            seg2 = strip_zeros(seg2);
            // Whichever number has more digits wins.
            if seg1.len() != seg2.len() {
                return seg1.len().cmp(&seg2.len());
            }
        }
        let rc = seg1.cmp(seg2);
        if rc != Ordering::Equal {
            return rc;
        }
    }

    // Everything compared identically; only separators may differ.
    if i >= one.len() && j >= two.len() {
        return Ordering::Equal;
    }
    // The final showdown: a remaining alphabetic string never beats an
    // empty one.
    let one_empty = i >= one.len();
    let two_alpha = j < two.len() && two[j].is_ascii_alphabetic();
    let one_alpha = i < one.len() && one[i].is_ascii_alphabetic();
    if (one_empty && !two_alpha) || one_alpha {
        Ordering::Less
    } else {
        Ordering::Greater
    }
}

fn strip_zeros(s: &[u8]) -> &[u8] {
    let n = s.iter().take_while(|&&c| c == b'0').count();
    &s[n..]
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cmp(a: &str, b: &str) -> i8 {
        match vercmp(a, b) {
            Ordering::Less => -1,
            Ordering::Equal => 0,
            Ordering::Greater => 1,
        }
    }

    #[test]
    fn agrees_with_pacman_s_vercmp_binary() {
        // Every row was checked against `vercmp` on an Arch machine.
        let table: &[(&str, &str, i8)] = &[
            ("1.5.0", "1.5.0", 0),
            ("1.5.1", "1.5.0", 1),
            ("1.5.1", "1.5", 1),
            ("1.5.0-1", "1.5.0-2", -1),
            ("1.5", "1.5-1", 0),
            ("1.0-1", "1.1", -1),
            ("1.5b-1", "1.5-1", -1),
            ("1.0a", "1.0alpha", -1),
            ("1.0alpha", "1.0b", -1),
            ("1.0beta", "1.0rc", -1),
            ("1.0rc", "1.0", -1),
            ("1.5.0", "1.5.a", 1),
            ("1.5a", "1.5", -1),
            ("1.0", "1.0.0", -1),
            ("1", "1.0", -1),
            ("1.0", "1.0a", 1),
            ("1:1.0", "1.0", 1),
            ("1:1.0", "2.0", 1),
            ("1:1.0", "1:2.0", -1),
            ("0:1.0", "1.0", 0),
            ("1.0~rc1", "1.0", 1),
            ("1.0~rc1", "1.0~rc2", -1),
            ("1.0~", "1.0", 1),
            ("1.0+", "1.0", 1),
            ("1.0.0.87", "1.0.0.87-3", 0),
            ("20260821", "20260820-1", 1),
            ("r16.961702d-1", "r17.abc-1", -1),
            ("0.10.7-1", "0.9.9-1", 1),
            ("1.02", "1.2", 0),
            ("1.10", "1.9", 1),
            ("001.002", "1.2", 0),
            ("1.0_1", "1.0.1", 0),
            ("1.0..1", "1.0.1", 1),
            ("2020.01.01", "2020.1.1", 0),
        ];
        for (a, b, want) in table {
            assert_eq!(cmp(a, b), *want, "vercmp({a}, {b})");
            assert_eq!(cmp(b, a), -*want, "vercmp({b}, {a})");
        }
    }
}
