// Generated from https://flathub.org/api/v2/appstream/<id> by tools in the
// scratchpad on 2026-09-12; the URLs are real so a browser shows real icons and
// screenshots. Regenerate rather than edit. Descriptions are the first blocks
// of what Flathub publishes, so they read as upstream wrote them.

export interface FlathubShot {
  image: string;
  thumb: string;
  width: number;
  height: number;
  caption: string | null;
}

export interface FlathubEntry {
  name: string;
  summary: string;
  description: string | null;
  icon: string;
  developer: string | null;
  categories: string[];
  licence: string | null;
  homepage: string | null;
  version: string | null;
  updated: number | null;
  screenshots: FlathubShot[];
}

export const FLATHUB: Record<string, FlathubEntry> = {
  "com.valvesoftware.Steam": {
    name: "Steam",
    summary: "Launcher for the Steam software distribution service",
    description: "<p>**Note: This is a community package of Steam gaming platform not officially supported by Valve.**</p><p>Steam is a software distribution service with an online store, automated installation, automatic updates, achievements, SteamCloud synchronized savegame and screenshot functionality, and many social features.</p><p>Note: To add a game library on another drive, first you need to grant the app access to it:</p><p>flatpak override --user --filesystem=/path/to/your/Steam/Library com.valvesoftware.Steam</p>",
    icon: "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/icons/128x128/com.valvesoftware.Steam.png",
    developer: "Valve Corporation",
    categories: ["Game", "PackageManager"],
    licence: "LicenseRef-proprietary",
    homepage: "https://store.steampowered.com/",
    version: "1.0.0.85",
    updated: 1755561600,
    screenshots: [{"image": "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/screenshots/image-1_624x533@1.png", "width": 1200, "height": 1026, "caption": "The main Steam library window"}, {"image": "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/screenshots/image-2_624x351@1.png", "width": 1280, "height": 720, "caption": "Steam Store interface"}, {"image": "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/com/valvesoftware/Steam/f0343a4b277e822cce53b904454d3a7d/screenshots/image-3_624x302@1.png", "width": 1200, "height": 582, "caption": null}],
  },
  "org.gimp.GIMP": {
    name: "GNU Image Manipulation Program",
    summary: "High-end image creation and manipulation",
    description: "<p> GIMP is an acronym for GNU Image Manipulation Program. It is Community-driven Free Software for high-end image creation and manipulation. </p><p> It has many capabilities. It can be used as a paint program, an expert quality photo retouching program, image composition, an online batch processing system, a mass production image renderer, an image format converter, etc. </p><p> GIMP is expandable and extensible. It is designed to be augmented with plug-ins and extensions to do just about anything. The advanced scripting interface allows everything from the simplest task to the most complex image manipulation procedures to be easily scripted. GIMP is available for Linux, Microsoft Windows and macOS. </p>",
    icon: "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/icons/128x128/org.gimp.GIMP.png",
    developer: "The GIMP team",
    categories: ["Graphics", "2DGraphics", "RasterGraphics"],
    licence: "GPL-3.0+ AND LGPL-3.0+",
    homepage: "https://www.gimp.org/",
    version: "3.2.6",
    updated: 1788998400,
    screenshots: [{"image": "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/screenshots/image-1_624x351@1.png", "width": 1920, "height": 1080, "caption": "Scene 4 cut 15 of \"ZeMarmot\" being edited in GIMP. Illustration by Aryeom (CC by-sa 4.0 International)"}, {"image": "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/screenshots/image-2_624x340@1.png", "width": 1920, "height": 1048, "caption": "Gull on beach photograph being edited in GIMP. Photo by Iana (CC by-sa 4.0 International)"}, {"image": "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/gimp/GIMP/4135d7fcf94290507c24bd93761fd4d5/screenshots/image-3_624x340@1.png", "width": 1920, "height": 1048, "caption": "Portrait of Sofiia being edited in GIMP. Photo by Sofia (CC by-sa 4.0 International)"}],
  },
  "org.mozilla.firefox": {
    name: "Firefox",
    summary: "Fast, Private & Safe Web Browser",
    description: "<p>When it comes to your life online, you have a choice: accept the factory settings or put your privacy first. When you choose Firefox as your default browser, you’re choosing to protect your data while supporting an independent tech company. Firefox is also the only major browser backed by a non-profit fighting to give you more openness, transparency and control of your life online. Join hundreds of millions of people who choose to protect what's important by choosing Firefox - a web browser designed to be fast, easy to use, customizable and private.</p>",
    icon: "https://dl.flathub.org/media/icons/128x128/org.mozilla.firefox.png",
    developer: "Mozilla",
    categories: ["Network", "WebBrowser"],
    licence: "MPL-2.0",
    homepage: "https://www.mozilla.org/firefox/",
    version: "155.0.1",
    updated: 1788393600,
    screenshots: [{"image": "https://dl.flathub.org/media/org.mozilla.firefox-stable/1504x846/org.mozilla.firefox-af5d1ae7c121ea4864b3c5a1098f8f9c.png", "thumb": "https://dl.flathub.org/media/org.mozilla.firefox-stable/624x351/org.mozilla.firefox-af5d1ae7c121ea4864b3c5a1098f8f9c.png", "width": 1504, "height": 846, "caption": null}, {"image": "https://dl.flathub.org/media/org.mozilla.firefox-stable/1504x846/org.mozilla.firefox-c6f98b38b8b28b113a75a6b34037b759.png", "thumb": "https://dl.flathub.org/media/org.mozilla.firefox-stable/624x351/org.mozilla.firefox-c6f98b38b8b28b113a75a6b34037b759.png", "width": 1504, "height": 846, "caption": null}, {"image": "https://dl.flathub.org/media/org.mozilla.firefox-stable/1504x846/org.mozilla.firefox-60e855c1f4180607e40c9762a0fb9fa6.png", "thumb": "https://dl.flathub.org/media/org.mozilla.firefox-stable/624x351/org.mozilla.firefox-60e855c1f4180607e40c9762a0fb9fa6.png", "width": 1504, "height": 846, "caption": null}],
  },
  "org.videolan.VLC": {
    name: "VLC",
    summary: "VLC media player, the open-source multimedia player",
    description: "<p> VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols. </p>",
    icon: "https://dl.flathub.org/media/org/videolan/VLC/34e7c2b6a026c5c290606225a84582d3/icons/128x128/org.videolan.VLC.png",
    developer: "VideoLAN et al.",
    categories: ["AudioVideo", "Player", "Recorder"],
    licence: "GPL-2.0+",
    homepage: "https://www.videolan.org/vlc/",
    version: "3.0.23",
    updated: 1767225600,
    screenshots: [{"image": "https://dl.flathub.org/media/org/videolan/VLC/34e7c2b6a026c5c290606225a84582d3/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/videolan/VLC/34e7c2b6a026c5c290606225a84582d3/screenshots/image-1_624x351@1.png", "width": 1280, "height": 720, "caption": null}, {"image": "https://dl.flathub.org/media/org/videolan/VLC/34e7c2b6a026c5c290606225a84582d3/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/videolan/VLC/34e7c2b6a026c5c290606225a84582d3/screenshots/image-2_624x351@1.png", "width": 1280, "height": 720, "caption": null}],
  },
  "org.blender.Blender": {
    name: "Blender",
    summary: "Free and open source 3D creation suite",
    description: "<p> Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline, modeling, rigging, animation, simulation, rendering, compositing, motion tracking, and video editing. </p><p> Blender is a public project, made by hundreds of people from around the world; by studios and individual artists, professionals and hobbyists, scientists, students, VFX experts, animators, game artists, modders, and the list goes on. </p>",
    icon: "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/icons/128x128/org.blender.Blender.png",
    developer: "Blender Foundation",
    categories: ["Graphics", "3DGraphics"],
    licence: "GPL-3.0",
    homepage: "https://www.blender.org",
    version: "5.2",
    updated: 1783987200,
    screenshots: [{"image": "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/screenshots/image-1_624x351@1.png", "width": 2555, "height": 1440, "caption": "Sculpt"}, {"image": "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/screenshots/image-2_624x351@1.png", "width": 1920, "height": 1080, "caption": "Model"}, {"image": "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/blender/Blender/c6b07403115901571923d99f1b725b0e/screenshots/image-3_624x351@1.png", "width": 1920, "height": 1080, "caption": "Animate"}],
  },
  "org.inkscape.Inkscape": {
    name: "Inkscape",
    summary: "Vector Graphics Editor",
    description: "<p> A Free and open source vector graphics editor. It offers a rich set of features and is widely used for both artistic and technical illustrations such as cartoons, clip art, logos, typography, diagramming and flowcharting. </p><p> It uses vector graphics to allow for sharp printouts and renderings at unlimited resolution and is not bound to a fixed number of pixels like raster graphics. Inkscape uses the standardized SVG file format as its main format, which is supported by many other applications including web browsers. </p><p> Inkscape supports many advanced SVG features (markers, clones, alpha blending, etc.) and great care is taken in designing a streamlined interface. It is very easy to edit nodes, perform complex path operations, trace bitmaps and much more. We also aim to maintain a thriving user and developer community by using open, community-oriented development. </p>",
    icon: "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/icons/128x128/org.inkscape.Inkscape.png",
    developer: "The Inkscape Community",
    categories: ["Graphics"],
    licence: "GPL-2.0-or-later",
    homepage: "https://inkscape.org",
    version: "1.4.4",
    updated: 1778025600,
    screenshots: [{"image": "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/screenshots/image-1_624x383@1.png", "width": 2261, "height": 1390, "caption": "Editing a Flatpak Logo"}, {"image": "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/screenshots/image-2_624x382@1.png", "width": 2260, "height": 1386, "caption": "Multipage editing"}, {"image": "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/inkscape/Inkscape/d06b79da7ad6df73032683fbcf8c4d56/screenshots/image-3_624x382@1.png", "width": 2260, "height": 1384, "caption": "Editing with Inkscape"}],
  },
  "com.discordapp.Discord": {
    name: "Discord",
    summary: "Talk, play, hang out",
    description: "<p>Discord is a free all in one messaging, voice, and video client thats available on your computer and phone.</p><p>Whether you’re part of a school club, gaming group, worldwide art community, or just a handful of friends that want to spend time together, Discord makes it easy to talk every day and hang out more often.</p><ul><li>Talk to your friends with messaging, voice, and video in a \"Direct Message\" (1 other person), group chat (up to 10 people), or a multi-channel server (practically infinite maximum members).</li><li>Discord servers are organized into topic-based channels where you can collaborate, share, and just talk about your day without clogging up a group chat.</li><li>Grab a seat in a voice channel when you’re free. Friends in your server can see you’re around and instantly pop in to talk without having to call.</li><li>Get a community of any size running with moderation tools and custom member access. Give members special powers, set up private channels, and more.</li><li>Low-latency voice and video feels like you’re in the same room. Wave hello over video, watch friends stream their games, or gather up and have a drawing session with screen share.</li><li>Available on Linux, macOS, Windows, iOS, Android, and your web browser.</li></ul><p>Discord is written in Javascript, React, Elixir, and Rust. The desktop application uses the electron framework.</p>",
    icon: "https://dl.flathub.org/media/com/discordapp/Discord/216c86b47606bcb3e53a965e3050d407/icons/128x128/com.discordapp.Discord.png",
    developer: "Discord Inc.",
    categories: ["InstantMessaging", "Network"],
    licence: "LicenseRef-proprietary",
    homepage: "https://discord.com",
    version: "1.0.157",
    updated: 1788825600,
    screenshots: [{"image": "https://dl.flathub.org/media/com/discordapp/Discord/216c86b47606bcb3e53a965e3050d407/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/discordapp/Discord/216c86b47606bcb3e53a965e3050d407/screenshots/image-1_624x478@1.png", "width": 2374, "height": 1822, "caption": "Dark Mode Window"}, {"image": "https://dl.flathub.org/media/com/discordapp/Discord/216c86b47606bcb3e53a965e3050d407/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/com/discordapp/Discord/216c86b47606bcb3e53a965e3050d407/screenshots/image-2_624x478@1.png", "width": 2374, "height": 1822, "caption": "Light Mode Window"}],
  },
  "com.spotify.Client": {
    name: "Spotify",
    summary: "Online music streaming service",
    description: "<p>Access all of your favorite music, discover new songs, and share music online with your friends - all in one place. Create shared playlists or share individual songs with your Facebook friends with just a click of a button. Follow your favorite artists or friends to know what they are listening to, and then save the songs to your own playlists. Spotify is the best way to have access to millions of songs and all the latest hits.</p>",
    icon: "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/icons/128x128/com.spotify.Client.png",
    developer: "Spotify",
    categories: ["Audio", "Music", "Player", "AudioVideo"],
    licence: "LicenseRef-proprietary",
    homepage: "https://www.spotify.com",
    version: "1.2.95.453.g0eeebbed",
    updated: 1786492800,
    screenshots: [{"image": "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/screenshots/image-1_624x351@1.png", "width": 1920, "height": 1080, "caption": "Artist"}, {"image": "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/screenshots/image-2_624x351@1.png", "width": 1920, "height": 1080, "caption": "Playlist"}, {"image": "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/com/spotify/Client/2be38d678bbcc0e04cec0c19c60a80fe/screenshots/image-3_624x351@1.png", "width": 1920, "height": 1080, "caption": "Podcast"}],
  },
  "com.obsproject.Studio": {
    name: "OBS Studio",
    summary: "Live stream and record videos",
    description: "<p>Free and open source software for video capturing, recording, and live streaming.</p><p>Features:</p><ul><li>High performance real time video/audio capturing and mixing. Create scenes made up of multiple sources including window captures, images, text, browser windows, webcams, capture cards and more.</li><li>Set up an unlimited number of scenes you can switch between seamlessly via custom transitions.</li><li>Intuitive audio mixer with per-source filters such as noise gate, noise suppression, and gain. Take full control with VST plugin support.</li><li>Powerful and easy to use configuration options. Add new Sources, duplicate existing ones, and adjust their properties effortlessly.</li><li>Streamlined Settings panel gives you access to a wide array of configuration options to tweak every aspect of your broadcast or recording.</li><li>Modular 'Dock' UI allows you to rearrange the layout exactly as you like. You can even pop out each individual Dock to its own window.</li></ul><p>Create Professional Productions:</p>",
    icon: "https://dl.flathub.org/media/com/obsproject/Studio/b24d8f7f7f9672e48342e70759b01e5e/icons/128x128/com.obsproject.Studio.png",
    developer: "OBS Project",
    categories: ["AudioVideo", "Recorder"],
    licence: "GPL-2.0-or-later",
    homepage: "https://obsproject.com",
    version: "32.2.2",
    updated: 1786665600,
    screenshots: [{"image": "https://dl.flathub.org/media/com/obsproject/Studio/b24d8f7f7f9672e48342e70759b01e5e/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/obsproject/Studio/b24d8f7f7f9672e48342e70759b01e5e/screenshots/image-1_624x436@1.png", "width": 1000, "height": 700, "caption": "The OBS Studio window showing a card game, the project website, a video, and a purple rectangle"}],
  },
  "org.kde.kdenlive": {
    name: "Kdenlive",
    summary: "Video editor",
    description: "<p>Kdenlive is a video editing application with support for many audio and video formats. It offers advanced editing features, a variety of effects and transitions, color correction, audio post-production and subtitling tools. Additionally, it provides the flexibility to render into practically any format of your choice.</p><p>Features:</p><ul><li>Nested Sequences</li><li>Configurable interface and shortcuts</li><li>Scopes: Histogram, Vectorscope, RGB Parade, Waveform and Audio Meter</li><li>Proxy editing</li><li>Free online assets and templates</li><li>Motion tracking</li><li>AI powered tools</li></ul>",
    icon: "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/icons/128x128/org.kde.kdenlive.desktop.png",
    developer: "KDE",
    categories: ["AudioVideo", "AudioVideoEditing"],
    licence: "GPL-3.0-only",
    homepage: "https://kdenlive.org/?mtm_campaign=appstream_data&mtm_kwd=homepage",
    version: "26.08.1",
    updated: 1788998400,
    screenshots: [{"image": "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/screenshots/image-1_624x369@1.png", "width": 1373, "height": 813, "caption": "Dark theme"}, {"image": "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/screenshots/image-2_624x356@1.png", "width": 1912, "height": 1091, "caption": "Default interface"}, {"image": "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/kde/kdenlive.desktop/28bad987721e9df9cd2c254eb376bb11/screenshots/image-3_624x358@1.png", "width": 2691, "height": 1544, "caption": "Color correction"}],
  },
  "org.libreoffice.LibreOffice": {
    name: "LibreOffice",
    summary: "The LibreOffice productivity suite",
    description: "<p>LibreOffice is a powerful office suite. Its clean interface and feature-rich tools help you unleash your creativity and enhance your productivity. LibreOffice includes several applications that make it the most powerful Free and Open Source office suite on the market: Writer (word processing), Calc (spreadsheets), Impress (presentations), Draw (vector graphics and flowcharts), Base (databases), and Math (formula editing).</p><p>LibreOffice supports opening and saving into a wide variety of formats, so you can easily share documents with users of other popular office suites without worrying about compatibility.</p>",
    icon: "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/icons/128x128/org.libreoffice.LibreOffice.png",
    developer: "The Document Foundation",
    categories: ["Office"],
    licence: "MPL-2.0",
    homepage: "http://www.libreoffice.org/discover/libreoffice/",
    version: "26.8.0.3",
    updated: 1788393600,
    screenshots: [{"image": "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/screenshots/image-1_624x436@1.png", "width": 1518, "height": 1063, "caption": "Sample Writer document"}, {"image": "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/screenshots/image-2_624x362@1.png", "width": 1470, "height": 853, "caption": "Sample Calc document"}, {"image": "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/libreoffice/LibreOffice/ebfb52f9f2e593b5b0919bb903a7fe64/screenshots/image-3_624x453@1.png", "width": 1469, "height": 1067, "caption": "Sample Impress document"}],
  },
  "org.kde.krita": {
    name: "Krita",
    summary: "Digital Painting, Creative Freedom",
    description: "<p>This flatpak is community maintained. Please report Flatpak specific bugs that do not occur on the upstream AppImage at https://github.com/flathub/org.kde.krita/issues.</p><p>Krita is the full-featured digital art studio.</p><p>It is perfect for sketching and painting, and presents an end–to–end solution for creating digital painting files from scratch by masters.</p><p> Krita is a great choice for creating concept art, comics, textures for rendering and matte paintings. Krita supports many colorspaces like RGB and CMYK at 8 and 16 bits integer channels, as well as 16 and 32 bits floating point channels. </p>",
    icon: "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/icons/128x128/org.kde.krita.png",
    developer: "Krita Foundation",
    categories: ["Graphics", "2DGraphics", "RasterGraphics"],
    licence: "GPL-3.0-only",
    homepage: "https://www.krita.org/",
    version: "5.3.3",
    updated: 1784764800,
    screenshots: [{"image": "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/screenshots/image-1_624x338@1.png", "width": 1920, "height": 1043, "caption": "Krita is a full-featured digital painting studio"}, {"image": "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/screenshots/image-2_624x338@1.png", "width": 1920, "height": 1043, "caption": "The startup window now also gives you the latest news about Krita"}, {"image": "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/kde/krita/2d1e8935a00814a3aae96df66090a85a/screenshots/image-3_624x351@1.png", "width": 1920, "height": 1080, "caption": "There are over ten immensely powerful brush engines"}],
  },
  "org.mozilla.Thunderbird": {
    name: "Thunderbird",
    summary: "Thunderbird is a free and open source email, newsfeed, chat, and calendaring client",
    description: "<p>Thunderbird is a free and open source email, newsfeed, chat, and calendaring client, that’s easy to set up and customize. One of the core principles of Thunderbird is the use and promotion of open standards - this focus is a rejection of our world of closed platforms and services that can’t communicate with each other. We want our users to have freedom and choice in how they communicate.</p><p>Thunderbird is an open source project, which means anyone can contribute ideas, designs, code, and time helping fellow users.</p>",
    icon: "https://dl.flathub.org/media/icons/128x128/org.mozilla.Thunderbird.png",
    developer: "MZLA Technologies, part of the Mozilla Foundation",
    categories: ["Calendar", "Chat", "ContactManagement", "Email", "Feed", "IRCClient", "InstantMessaging", "Network", "News", "Office"],
    licence: "MPL-2.0",
    homepage: "https://www.thunderbird.net/",
    version: "140.10.2esr",
    updated: 1778112000,
    screenshots: [{"image": "https://dl.flathub.org/media/org.mozilla.Thunderbird-stable/1504x846/org.mozilla.Thunderbird-6d680df8fa5a1a0c374882c019e09714.png", "thumb": "https://dl.flathub.org/media/org.mozilla.Thunderbird-stable/624x351/org.mozilla.Thunderbird-6d680df8fa5a1a0c374882c019e09714.png", "width": 1504, "height": 846, "caption": null}, {"image": "https://dl.flathub.org/media/org.mozilla.Thunderbird-stable/1504x846/org.mozilla.Thunderbird-70c1d7576c238e58e02e7ae0fcb7906b.png", "thumb": "https://dl.flathub.org/media/org.mozilla.Thunderbird-stable/624x351/org.mozilla.Thunderbird-70c1d7576c238e58e02e7ae0fcb7906b.png", "width": 1504, "height": 846, "caption": null}],
  },
  "org.telegram.desktop": {
    name: "Telegram",
    summary: "New era of messaging",
    description: "<p>Pure instant messaging, simple, fast, secure, and synced across all your devices. One of the world's top 10 most downloaded apps with over 500 million active users.</p><p>FAST: Telegram is the fastest messaging app on the market, connecting people via a unique, distributed network of data centers around the globe.</p><p>SYNCED: You can access your messages from all your phones, tablets and computers at once. Telegram apps are standalone, so you don’t need to keep your phone connected. Start typing on one device and finish the message from another. Never lose your data again.</p><p>UNLIMITED: You can send media and files, without any limits on their type and size. Your entire chat history will require no disk space on your device, and will be securely stored in the Telegram cloud for as long as you need it.</p>",
    icon: "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/icons/128x128/org.telegram.desktop.png",
    developer: "Telegram FZ-LLC",
    categories: ["Network", "InstantMessaging"],
    licence: "GPL-3.0",
    homepage: "https://desktop.telegram.org/",
    version: "7.1.5",
    updated: 1788307200,
    screenshots: [{"image": "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/screenshots/image-1_624x431@1.png", "width": 1892, "height": 1308, "caption": null}, {"image": "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/screenshots/image-2_624x390@1.png", "width": 2880, "height": 1800, "caption": "A lightning-fast native app that seamlessly syncs with your other devices"}, {"image": "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/telegram/desktop/6de0c57224464a5e26eb7d0c4632b5d5/screenshots/image-3_624x390@1.png", "width": 2880, "height": 1800, "caption": "A fully autonomous Telegram app, no phone connection required"}],
  },
  "org.signal.Signal": {
    name: "Signal Desktop",
    summary: "Private messenger",
    description: "<p> To use the Signal desktop app, Signal must first be installed on your phone. </p><p> Millions of people use Signal every day for free and instantaneous communication anywhere in the world. Send and receive high-fidelity messages, participate in HD voice/video calls, and explore a growing set of new features that help you stay connected. Signal’s advanced privacy-preserving technology is always enabled, so you can focus on sharing the moments that matter with the people who matter to you. </p><p> Signal is an independent 501c3 nonprofit. The complete source code for the Signal clients and the Signal server is available on GitHub. </p><p> This flatpak is maintained by the Flathub community, and is not necessarily endorsed or officially maintained by the upstream developers. </p>",
    icon: "https://dl.flathub.org/media/org/signal/Signal/4ffe6088d57d7704b3bfa6ef8f91cbb0/icons/128x128/org.signal.Signal.png",
    developer: "Signal Foundation",
    categories: ["Network", "InstantMessaging", "Chat"],
    licence: "AGPL-3.0-only",
    homepage: "https://signal.org/",
    version: "8.27.0",
    updated: 1788998400,
    screenshots: [{"image": "https://dl.flathub.org/media/org/signal/Signal/4ffe6088d57d7704b3bfa6ef8f91cbb0/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/signal/Signal/4ffe6088d57d7704b3bfa6ef8f91cbb0/screenshots/image-1_624x380@1.png", "width": 804, "height": 490, "caption": "Typical view of the window (Windows version)"}],
  },
  "com.bitwarden.desktop": {
    name: "Bitwarden",
    summary: "A secure and free password manager for all of your devices",
    description: "<p> Bitwarden is the easiest and safest way to store all of your logins and passwords while conveniently keeping them synced between all of your devices. </p><p> Password theft is a serious problem. The websites and apps that you use are under attack every day. Security breaches occur and your passwords are stolen. When you reuse the same passwords across apps and websites hackers can easily access your email, bank, and other important accounts. </p><p> Security experts recommend that you use a different, randomly generated password for every account that you create. But how do you manage all those passwords? Bitwarden makes it easy for you to create, store, and access your passwords. </p><p> Bitwarden stores all of your logins in an encrypted vault that syncs across all of your devices. Since it's fully encrypted before it ever leaves your device, only you have access to your data. Not even the team at Bitwarden can read your data, even if we wanted to. Your data is sealed with AES-256 bit encryption, salted hashing, and PBKDF2 SHA-256. </p>",
    icon: "https://dl.flathub.org/media/com/bitwarden/desktop/a658fdd56acda4f3ff25898c8855aa55/icons/128x128/com.bitwarden.desktop.png",
    developer: "Bitwarden Inc.",
    categories: ["Utility"],
    licence: "GPL-3.0",
    homepage: "https://www.bitwarden.com/",
    version: "2026.8.0",
    updated: 1787184000,
    screenshots: [{"image": "https://dl.flathub.org/media/com/bitwarden/desktop/a658fdd56acda4f3ff25898c8855aa55/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/bitwarden/desktop/a658fdd56acda4f3ff25898c8855aa55/screenshots/image-1_624x374@1.png", "width": 2400, "height": 1440, "caption": "Bitwarden on multiple devices"}],
  },
  "com.usebottles.bottles": {
    name: "Bottles",
    summary: "Run Windows software",
    description: "<p>Bottles lets you run Windows software on Linux, such as applications and games. It introduces a workflow that helps you organize by categorizing each software to your liking. Bottles provides several tools and integrations to help you manage and optimize your applications.</p><p>Features:</p><ul><li>Use pre-configured environments as a base</li><li>Change runners for any bottle</li><li>Various optimizations and options for gaming</li><li>Repair in case software or bottle is broken</li><li>Install various known dependencies</li><li>Integrated task manager to manage and monitor processes</li><li>Backup and restore</li></ul>",
    icon: "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/icons/128x128/com.usebottles.bottles.png",
    developer: "The Bottles Contributors",
    categories: ["Utility", "Game", "Graphics", "3DGraphics", "Emulator", "GNOME", "GTK"],
    licence: "GPL-3.0-only",
    homepage: "https://usebottles.com",
    version: "67.3",
    updated: 1788739200,
    screenshots: [{"image": "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/screenshots/image-1_624x486@1.png", "width": 979, "height": 763, "caption": "Bottles List Page"}, {"image": "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/screenshots/image-2_624x486@1.png", "width": 979, "height": 763, "caption": "Library Page"}, {"image": "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/com/usebottles/bottles/93451cd2dcca93e8be020ebbf22c1e2a/screenshots/image-3_624x486@1.png", "width": 979, "height": 763, "caption": "Create New Bottle"}],
  },
  "net.lutris.Lutris": {
    name: "Lutris",
    summary: "Video game preservation platform",
    description: "<p>Lutris helps you install and play video games from all eras and from most gaming systems. By leveraging and combining existing emulators, engine re-implementations and compatibility layers, it gives you a central interface to launch all your games.</p>",
    icon: "https://dl.flathub.org/media/net/lutris/Lutris/3cc8d32fd68604816f0a5f6872bf91b5/icons/128x128/net.lutris.Lutris.png",
    developer: "Lutris Team",
    categories: ["Game", "PackageManager"],
    licence: "GPL-3.0-or-later",
    homepage: "https://lutris.net",
    version: "0.5.22",
    updated: 1771891200,
    screenshots: [{"image": "https://dl.flathub.org/media/net/lutris/Lutris/3cc8d32fd68604816f0a5f6872bf91b5/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/net/lutris/Lutris/3cc8d32fd68604816f0a5f6872bf91b5/screenshots/image-1_624x403@1.png", "width": 1674, "height": 1083, "caption": "Main window"}],
  },
  "com.heroicgameslauncher.hgl": {
    name: "Heroic",
    summary: "Play Epic, GOG and Amazon Games",
    description: "<p>Heroic is an Open Source Games Launcher. Right now it supports launching games from the Epic Games Store using Legendary, GOG Games using our custom implementation with gogdl and Amazon Games using Nile.</p><p>Main Features:</p><ul><li>Have access to your Epic, GOG and Amazon Games in a intuitive User Interface.</li><li>Add Games outside GOG, Amazon or Epic Games Store native or not. Even Browser apps are supported</li><li>A Download queue to download multiple games at once.</li><li>Install and launch your Windows Games using Wine or Proton. Or Launch your Native GOG Games.</li><li>Cloud Saves support for GOG and Epic Games.</li><li>Import Games installed through the Epic Store or GOG Galaxy.</li><li>Verify and Repair corrupted installations or even move your installation to different folders.</li><li>Integrated Proton/Wine Manager for easy installation of new and updated ones</li><li>Integrated Winetricks</li><li>Support for install and uninstall of Games DLCs</li><li>Access the Epic and GOG store and also Heroic Wiki directly from the App.</li><li>Check Metacritic, IGCB or OpenCritic score for the game.</li><li>And many more features</li></ul><p>Current Limitations on the Flatpak:</p>",
    icon: "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/icons/128x128/com.heroicgameslauncher.hgl.png",
    developer: "Heroic Games Launcher",
    categories: ["Game", "PackageManager"],
    licence: "GPL-3.0",
    homepage: "https://heroicgameslauncher.com",
    version: "v2.22.1",
    updated: 1786233600,
    screenshots: [{"image": "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/screenshots/image-1_624x436@1.png", "width": 2000, "height": 1400, "caption": "Library"}, {"image": "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/screenshots/image-2_624x436@1.png", "width": 2000, "height": 1400, "caption": "GamePage"}, {"image": "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/com/heroicgameslauncher/hgl/7c9401fb986461cf52a549d0514c83b9/screenshots/image-3_624x436@1.png", "width": 2000, "height": 1400, "caption": "Stores"}],
  },
  "net.davidotek.pupgui2": {
    name: "ProtonUp-Qt",
    summary: "Install Wine- and Proton-based compatibility tools",
    description: "<p> Install and manage Wine- and Proton-based compatibility tools for Steam and Lutris with this graphical user interface. </p><p>Supported launchers:</p><ul><li>Steam</li><li>Lutris</li><li>Heroic Games Launcher</li><li>Bottles</li><li>WineZGUI</li><li>Both normal, Snap and Flatpak installations are supported</li></ul><p>Supported compatibility tools:</p>",
    icon: "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/icons/128x128/net.davidotek.pupgui2.png",
    developer: "DavidoTek",
    categories: ["Game", "Utility"],
    licence: "GPL-3.0",
    homepage: "https://davidotek.github.io/protonup-qt",
    version: "2.15.1",
    updated: 1782259200,
    screenshots: [{"image": "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/screenshots/image-1_624x351@1.png", "width": 800, "height": 450, "caption": null}, {"image": "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/screenshots/image-2_624x351@1.png", "width": 800, "height": 450, "caption": null}, {"image": "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/net/davidotek/pupgui2/0b76438e92ef510678852b8b540ecc67/screenshots/image-3_624x351@1.png", "width": 1600, "height": 900, "caption": null}],
  },
  "dev.zed.Zed": {
    name: "Zed",
    summary: "High-performance code editor",
    description: "<p> Productive coding starts with a tool that stays out of your way. Zed blends the power of an IDE with the speed of a lightweight editor for productivity you can feel under your fingertips. </p><p>Features:</p><ul><li>Performance: Efficiently uses every CPU core and your GPU for instant startup, quick file loading, and responsive keystrokes.</li><li>Language-aware: Maintains a syntax tree for precise highlighting, and auto-indent, with LSP support for autocompletion and refactoring.</li><li>Collaboration: Real-time editing and navigation for multiple developers in a shared workspace.</li><li>AI Integration: Integrates GitHub Copilot and GPT-4 for natural language code generation.</li></ul>",
    icon: "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/icons/128x128/dev.zed.Zed.png",
    developer: "Zed Industries, Inc.",
    categories: ["Development", "Utility"],
    licence: "AGPL-3.0-or-later and Apache-2.0 and GPL-3.0-or-later",
    homepage: "https://zed.dev",
    version: "v1.19.2",
    updated: 1788912000,
    screenshots: [{"image": "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/screenshots/image-1_624x477@1.png", "width": 1122, "height": 859, "caption": "Zed with a large project open, showing language server and gitblame support"}, {"image": "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/screenshots/image-2_624x477@1.png", "width": 1122, "height": 859, "caption": "Zed with a file open and a channel message thread in the right sidebar"}, {"image": "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/dev/zed/Zed/7bf00639513a6881b2a319fde286aba0/screenshots/image-3_624x477@1.png", "width": 1122, "height": 859, "caption": "Example of a channel's shared document"}],
  },
  "com.visualstudio.code": {
    name: "Visual Studio Code",
    summary: "Code editing. Redefined.",
    description: "<p>**NOTE: This is the proprietary Microsoft build of Visual Studio Code, packaged into a Flatpak. This repackaging is not supported by Microsoft.**</p><p>Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle.</p><p>IMPORTANT: To use certain features in this flatpacked version (like the integrated terminal), please read the linked documentation.</p>",
    icon: "https://dl.flathub.org/media/com/visualstudio/code/654c0d747c53bd455cce9eea7cf2d36c/icons/128x128/com.visualstudio.code.png",
    developer: "Microsoft Corporation",
    categories: ["TextEditor", "Development", "IDE"],
    licence: "LicenseRef-proprietary",
    homepage: "https://code.visualstudio.com",
    version: "1.137.0",
    updated: 1788912000,
    screenshots: [{"image": "https://dl.flathub.org/media/com/visualstudio/code/654c0d747c53bd455cce9eea7cf2d36c/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/visualstudio/code/654c0d747c53bd455cce9eea7cf2d36c/screenshots/image-1_624x339@1.png", "width": 2376, "height": 1291, "caption": "Editing TypeScript"}],
  },
  "md.obsidian.Obsidian": {
    name: "Obsidian",
    summary: "Markdown-based knowledge base",
    description: "<p>Obsidian is a powerful knowledge base that works on top of a local folder of plain text Markdown files. In Obsidian, making and following connections is frictionless, and with the connections in place, you can explore all of your knowledge in the interactive graph view. Obsidian supports CommonMark and GitHub Flavored Markdown (GFM), along with other useful notetaking features such as tags, LaTeX mathematical expressions, mermaid diagrams, footnotes, internal links and embedding Obsidian notes or external files. Obsidian also has a plugin system with 20+ supported plugins to expand its capabilities.</p><p>The documentation can be accessed by opening the demo vault that is shipped in Obsidian.</p><p>Obsidian is free for all purposes, including personal, commercial, and non-profit use. No account or license is required for qualifying use cases described in the End User License Agreement. Users have the option to purchase a Catalyst license to get early access to insider builds and support the development. Additionally, Obsidian offers optional paid services for publishing and synchronizing your notes. Details about these optional hosted services can be found on the Obsidian website.</p><p>This distribution is verified by the Obsidian team but isn't supported</p>",
    icon: "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/icons/128x128/md.obsidian.Obsidian.png",
    developer: "Obsidian",
    categories: ["Office"],
    licence: "LicenseRef-proprietary",
    homepage: "https://obsidian.md/",
    version: "1.13.7",
    updated: 1786492800,
    screenshots: [{"image": "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/screenshots/image-1_624x330@1.png", "width": 2560, "height": 1357, "caption": "Screenshot of Obsidian's main interface"}, {"image": "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/screenshots/image-2_624x716@1.png", "width": 1170, "height": 1344, "caption": "Examples of Obsidian's basic text formatting capabilities"}, {"image": "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/md/obsidian/Obsidian/56e379aaf3973395285fb351884e0fb9/screenshots/image-3_624x436@1.png", "width": 1752, "height": 1226, "caption": "Screenshot of Obsidian's graph view"}],
  },
  "io.mpv.Mpv": {
    name: "mpv",
    summary: "A free, open source, and cross-platform media player",
    description: "<p> Mpv is a movie player based on MPlayer and mplayer2. It supports a wide variety of video file formats, audio and video codecs, and subtitle types. Special input URL types are available to read input from a variety of sources other than disk files. Depending on platform, a variety of different video and audio output methods are supported. </p><p>Features:</p><ul><li>Drag and drop playlist</li><li>Loading external configuration files</li><li>Flatpak: mpv-mpris support - multimedia keys play/pause support</li><li>Flatpak: mpv.conf: Screenshots (shortcut key 's') are saved in ~/Pictures/mpv directory</li><li>Flatpak: mpv config directory is ~/.var/app/io.mpv.Mpv/config/mpv</li><li>Flatpak: mpv scripts directory is ~/.var/app/io.mpv.Mpv/config/mpv/scripts</li><li>Flatpak: mpv_inhibit_gnome is included which prevents screen blanking in GNOME while playing media</li><li>Flatpak: mpv scripts needs write access. Use flatseal app to set home or host write permission</li></ul>",
    icon: "https://dl.flathub.org/media/io/mpv/Mpv/4021dec7d90c2c9591fef27ba6a04f5b/icons/128x128/io.mpv.Mpv.png",
    developer: "The mpv player contributors",
    categories: ["AudioVideo", "Audio", "Video", "Player", "TV"],
    licence: "GPL-2.0+ AND LGPL-2.0-or-later",
    homepage: "https://mpv.io/",
    version: "v0.41.0",
    updated: 1766275200,
    screenshots: [{"image": "https://dl.flathub.org/media/io/mpv/Mpv/4021dec7d90c2c9591fef27ba6a04f5b/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/io/mpv/Mpv/4021dec7d90c2c9591fef27ba6a04f5b/screenshots/image-1_624x393@1.png", "width": 998, "height": 629, "caption": "The main window showing the application in action"}],
  },
  "org.audacityteam.Audacity": {
    name: "Audacity",
    summary: "Audacity is the world's most popular audio editing and recording app",
    description: "<p>Audacity is the world's most popular audio editing and recording app.</p><p>You can use Audacity to:</p><ul><li>Record live audio</li><li>Convert tapes and records into digital recordings or CDs</li><li>Edit WAV, AIFF, FLAC, MP2, MP3 or Ogg Vorbis sound files</li><li>Cut, copy, splice or mix sounds together</li><li>Change the speed or pitch of a recording</li><li>Apply a wide range of other effects to audio recordings</li><li>and much more!</li></ul>",
    icon: "https://dl.flathub.org/media/org/audacityteam/Audacity/0ad4a24524b6c06220649dc83a08ae81/icons/128x128/org.audacityteam.Audacity.png",
    developer: "Muse Group",
    categories: ["AudioVideo", "Audio"],
    licence: "GPL-3.0-only",
    homepage: "https://www.audacityteam.org/",
    version: "3.7.8",
    updated: 1779753600,
    screenshots: [{"image": "https://dl.flathub.org/media/org/audacityteam/Audacity/0ad4a24524b6c06220649dc83a08ae81/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/audacityteam/Audacity/0ad4a24524b6c06220649dc83a08ae81/screenshots/image-1_624x392@1.png", "width": 1148, "height": 723, "caption": "Main Window"}],
  },
  "org.godotengine.Godot": {
    name: "Godot Engine",
    summary: "Easily create 2D and 3D games",
    description: "<p>The feature-packed, cross-platform game engine to create 2D and 3D games from a unified interface. Godot Engine provides a comprehensive set of common tools, so that you can focus on making games without having to reinvent the wheel. Games can be exported in one click to a number of platforms, including the major desktop platforms (Linux, macOS, Windows) as well as mobile (Android, iOS), web-based (HTML5) platforms and consoles (Switch, PS4 and Xbox One - via thirdparty publishers).</p><p>Completely free and open source under the very permissive MIT license. No strings attached, no royalties, nothing. Your game is yours down to the last line of engine code. Godot's development is fully independent and community-driven, empowering you to help shape the engine to match your expectations. It is supported by the non-profit Godot Foundation.</p><p>Create games with ease, using Godot's unique approach to game development:</p><ul><li>Nodes for all your needs. Godot comes with hundreds of built-in nodes that make game design a breeze. You can also create your own for custom behaviors, editors and much more.</li><li>Flexible scene system. Create node compositions with support for instancing and inheritance.</li><li>Visual editor with all the tools you need packed into a beautiful and uncluttered context-sensitive UI.</li><li>Friendly content creation pipeline for artists, level designers, animators and everything in between.</li><li>Persistent live editing where changes are not lost after stopping the game. It even works on mobile devices!</li><li>Create your own custom tools with ease using the incredible tool system.</li></ul>",
    icon: "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/icons/128x128/org.godotengine.Godot.desktop.png",
    developer: "The Godot Engine Community",
    categories: ["Development", "IDE"],
    licence: "MIT",
    homepage: "https://godotengine.org/",
    version: "4.7.2",
    updated: 1787011200,
    screenshots: [{"image": "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/screenshots/image-1_624x358@1.png", "width": 1269, "height": 730, "caption": "Texture Viewer"}, {"image": "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/screenshots/image-2_624x351@1.png", "width": 1280, "height": 720, "caption": "Godot Editor (2D/UI view)"}, {"image": "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/godotengine/Godot.desktop/7d0473583b3a7a60927f7e289669a20c/screenshots/image-3_624x317@1.png", "width": 800, "height": 407, "caption": "Particle Viewer"}],
  },
  "org.prismlauncher.PrismLauncher": {
    name: "Prism Launcher",
    summary: "Custom Minecraft Launcher to easily manage multiple Minecraft installations at once",
    description: "<p>Prism Launcher is a custom launcher for Minecraft that focuses on predictability, long term stability and simplicity.</p><p>Features:</p><ul><li>Easily install game modifications, such as Fabric, Forge and Quilt</li><li>Easily install and update modpacks from the Launcher</li><li>Control your Java settings, and enable Mangohud or Gamemode with a toggle</li><li>Manage worlds and resource packs from the launcher</li><li>See logs and other details easily through a dashboard</li><li>Kill Minecraft in case of a crash/freeze</li><li>Isolate Minecraft instances to keep everything clean</li><li>Install and update mods directly from the launcher</li><li>Customize the launcher with themes, and more</li><li>And cat :3</li></ul>",
    icon: "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/icons/128x128/org.prismlauncher.PrismLauncher.png",
    developer: "Prism Launcher Contributors",
    categories: ["Game", "ActionGame", "AdventureGame", "Simulation", "PackageManager"],
    licence: "GPL-3.0-only",
    homepage: "https://prismlauncher.org/",
    version: "11.1.0",
    updated: 1320969600,
    screenshots: [{"image": "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/screenshots/image-1_624x462@1.png", "width": 1030, "height": 764, "caption": "The main Prism Launcher window"}, {"image": "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/screenshots/image-2_624x471@1.png", "width": 1126, "height": 850, "caption": "Modpack installation"}, {"image": "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/org/prismlauncher/PrismLauncher/eee17233b6a13761758f1159edee869a/screenshots/image-3_624x454@1.png", "width": 930, "height": 677, "caption": "Modpack updating"}],
  },
  "im.riot.Riot": {
    name: "Element",
    summary: "Secure communications platform built around you",
    description: "<p>More than group chat: communication</p><ul><li>Communicate with your team and out of network colleagues more efficiently: use dedicated rooms which persist information from their creation and forever.</li><li>Forget group emails: join or create rooms per topic, per team, per event… Decide the level of transparency you want to provide across the organisation or project.</li><li>Cut through the noise by creating notifications that are customised by you and for you.</li><li>Grab the attention of your colleague by calling out their name and don’t miss a thing with keyword alerts.</li><li>Deploy bots for fun or practical use with our integrations store.</li></ul><p>Preliminary Wayland support since 1.7.25.</p><p>To try running Element natively under Wayland, run:</p>",
    icon: "https://dl.flathub.org/media/im/riot/Riot/ebd473261fa37af55b552fe159734e13/icons/128x128/im.riot.Riot.png",
    developer: "Element Creations Ltd",
    categories: ["Network", "InstantMessaging", "Chat", "VideoConference"],
    licence: "AGPL-3.0-only OR GPL-3.0-only",
    homepage: "https://element.io/",
    version: "1.12.27",
    updated: 1788220800,
    screenshots: [{"image": "https://dl.flathub.org/media/im/riot/Riot/ebd473261fa37af55b552fe159734e13/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/im/riot/Riot/ebd473261fa37af55b552fe159734e13/screenshots/image-1_624x339@1.png", "width": 1920, "height": 1045, "caption": "Element logged-in frontend"}],
  },
  "com.github.johnfactotum.Foliate": {
    name: "Foliate",
    summary: "Read e-books in style",
    description: "<p>Discover a new chapter in reading with Foliate, the modern e-book reader tailored for GNOME. Immerse yourself in a distraction-free interface, with customization features designed to match your unique preferences.</p><p>Features include:</p><ul><li>Open EPUB, Mobipocket, Kindle, FB2, CBZ, and PDF files</li><li>Paginated mode and scrolled mode</li><li>Customize font and line-spacing</li><li>Light, sepia, dark, and invert mode</li><li>Reading progress slider with chapter marks</li><li>Bookmarks and annotations</li><li>Find in book</li><li>Quick dictionary lookup</li></ul>",
    icon: "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/icons/128x128/com.github.johnfactotum.Foliate.png",
    developer: "John Factotum",
    categories: ["Office", "Viewer"],
    licence: "GPL-3.0-or-later",
    homepage: "https://johnfactotum.github.io/foliate/",
    version: "3.3.0",
    updated: 1743465600,
    screenshots: [{"image": "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/screenshots/image-1_orig.png", "thumb": "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/screenshots/image-1_624x397@1.png", "width": 2644, "height": 1684, "caption": null}, {"image": "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/screenshots/image-2_orig.png", "thumb": "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/screenshots/image-2_624x397@1.png", "width": 2644, "height": 1684, "caption": null}, {"image": "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/screenshots/image-3_orig.png", "thumb": "https://dl.flathub.org/media/com/github/johnfactotum.Foliate/50c58d8da7fe3fa08d1fbf5174369d7d/screenshots/image-3_624x397@1.png", "width": 2644, "height": 1684, "caption": null}],
  },
};
